SHEETY_PRICES_ENDPOINT = "https://api.sheety.co/5f4bf42926e63aec53e487d48b4e6bd8/flightData/sheet1"
SHEETY_BEARER_TOKEN = "priajptivryvennbthikuanyttukutaamm"
AMADEUS_AUTH_URL = "https://test.api.amadeus.com/v1/security/oauth2/token"
AMADEUS_LOCATION_URL = "https://test.api.amadeus.com/v1/reference-data/locations"
AMADEUS_FLIGHT_OFFERS_URL = "https://test.api.amadeus.com/v2/shopping/flight-offers"
CLIENT_API = "1D2GveE42z206TbR7A1vKtQ1CalYUAgO"
CLIENT_SECRET_AUTH = "xg1ePvncwslQTWZT"
